# Generated by Django 4.0 on 2022-05-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='screening_start',
            new_name='screening_start_at',
        ),
    ]
