# Generated by Django 4.0 on 2022-04-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='on_billboard',
            field=models.BooleanField(default=True),
        ),
    ]
