# Generated by Django 4.0 on 2022-04-22 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auditorium.seat'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SeatReserved',
        ),
    ]
