# Generated by Django 4.0 on 2022-04-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_seat_delete_seatreserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
