# Generated by Django 4.0 on 2022-04-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_active_alter_reservation_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserved',
        ),
    ]
