# Generated by Django 4.0 on 2022-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='active',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='paid',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('NOT_USED', 'Not used'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='NOT_USED', max_length=128),
        ),
    ]
