# Generated by Django 4.0 on 2022-05-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_rename_active_reservation_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actived'), ('USED', 'Used'), ('EXPIRED', 'Expired')], max_length=128),
        ),
    ]
